jasypt:
  encryptor:
    password: salt
spring:
  datasource:
    url: jdbc:mysql://47.106.254.86/web?characterEncoding=utf8&useSSL=true
    username: lumnca
    password: chuan868
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: false
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"

